# Generated by Django 4.0.2 on 2022-02-15 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_conditiom_car_condition_alter_car_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 15, 44, 8, 472981)),
        ),
    ]
